version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/anscer-robotics
      - SESSION_SECRET=your_secret
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
